version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - ecommerce-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    hostname: zookeeper
    container_name: ecommerce-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    hostname: broker
    container_name: ecommerce-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-ui:
    image: provectuslabs/kafka-ui:latest # Ou use uma versão específica como provectuslabs/kafka-ui:0.7.0
    hostname: kafka-ui
    container_name: kafka-ui
    ports:
      - "8085:8080" # Porta para acessar a UI no seu navegador
    depends_on:
      - kafka # Certifique-se de que o Kafka esteja pronto antes da UI iniciar
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka-cluster # Nome do seu cluster na UI
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092 # Endereço do seu broker Kafka DENTRO da rede Docker
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181 # Endereço do Zookeeper DENTRO da rede Docker (opcional, mas bom ter)
      KAFKA_CLUSTERS_0_READONLY: "false" # Permite operações de escrita (criar/deletar tópicos, etc.)
      # KAFKA_CLUSTERS_0_SCHEMA_REGISTRY: http://schema-registry:8081 # Opcional: Se estiver usando Schema Registry
      # KAFKA_CLUSTERS_0_KAFKA_CONNECT: http://kafka-connect:8083 # Opcional: Se estiver usando Kafka Connect
      # KAFKA_CLUSTERS_0_JMX_PORT: 9999 # Opcional: Para monitoramento JMX avançado se o Kafka tiver JMX habilitado

volumes:
  postgres_data:
  redis_data:

networks:
  ecommerce-network:
    driver: bridge