server:
  port: 8081

grpc:
  server:
    port: 9090
    enable-reflection: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: ecommerce
    password: ecommerce
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    open-in-view: false
    generate-ddl: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      # Serializador para a chave da mensagem.
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Serializador para o valor da mensagem.
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      enable-auto-commit: false
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: '*'
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      # Propriedades do listener Spring Kafka (relacionadas ao @KafkaListener)
      ack-mode: RECORD # Modo de commit do offset.
        # RECORD: Commita o offset após cada registro ser processado com sucesso.
      # BATCH: Commita o offset após todos os registros do batch serem processados.
      # MANUAL: Commita manualmente (exige KafkaMessageListenerContainer.AckMode.MANUAL)
    topics:
      order-create: order-create

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  info:
    title: E-commerce Service API
    description: API para gerenciamento de e-commerce
    version: 1.0.0
    contact:
      name: Arthur Santana
      email: arthurgn.santana@gmail.com

# Configurações JWT
jwt:
  secret: 7JU9or21W3WnuZ+QnIu/Ksl6V1uGvfX3E5WvhT+Un2Qn+WXzKsX6GRHuJ+ho7AKt
  expirationAccessToken: 3600000  # 1 hora em milissegundos
  expirationRefreshToken: 604800000  # 7 dias em milissegundos